import '@/styles/globals.css'
import Head from 'next/head'
import { useEffect } from 'react'
import TagManager from "react-gtm-module"
import ReactGA from "react-ga"
import Header from '../components/Header'
import Footer from '../components/Footer'

const tagManagerArgs = {
  gtmId: "GTM-5K6CSK6Z",
};

const TRACKING_ID = "G-VFL11M5DLE"; // OUR_TRACKING_ID

export default function App({ Component, pageProps }) {

  useEffect(() => {
    TagManager.initialize(tagManagerArgs);
    ReactGA.initialize(TRACKING_ID);
  }, []);

  return (
    <>
      <Head>
        <title>Abbostop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <Component {...pageProps} />
      <Footer />
    </>
  ) 
}
